"""Independent report admission contract tests; these fixtures do not claim CAD truth.

The native Store omission/acceptance reproduction is retained separately under
81a7d567cf424654ba3ea883af348d16 and admission-replay-81f8e612....  Here the expected
obligation inventory is declared independently, never generated by the helper.
"""
import copy
import importlib.util
from pathlib import Path

import pytest

from oma.build_identity import checker_version
from oma.routing.network_scenario import SharedNetworkScenario
from oma.routing.selection import requires_physical_report_admission, validate_physical_report_admission
from oma.store import IntegrityError, digest

ROOT = next(parent for parent in Path(__file__).resolve().parents
    if (parent / "docs/ifc-network-spec.json").is_file() and (parent / "tests/test_network_scenario.py").is_file())
_fixture_spec = importlib.util.spec_from_file_location("admission_network_fixture", ROOT / "tests/test_network_scenario.py")
_fixture = importlib.util.module_from_spec(_fixture_spec)
_fixture_spec.loader.exec_module(_fixture)

ROUTE_CHECKS = (
    "fixed-request-assumptions", "protected-source-preservation", "materialized-input-integrity",
    "materialization-source-frame", "route-materialization-correspondence", "nominal-fabrication-witness-integrity",
    "fixed-service-obligations", "declared-terminal-state", "exported-physical-semantics",
    "physical-interference-and-clearance", "physical-self-interference", "physical-port-body-attachment",
    "permitted-zone-containment", "independent-objective-recomputation", "gravity-slope", "engineering-service")
NETWORK_CHECKS = (
    "fixed-network-requirements", "unique-network-demand-coverage", "protected-network-baseline",
    "network-source-and-datum-binding", "network-artifact-integrity", "network-native-semantics", "network-objective",
    "network-all-source-clearance", "network-all-component-pairs", "network-permitted-zone", "network-demand-conditioned-service")
JOINT_CHECKS = ("joint-demand-coverage", "protected-prior-missions", "joint-replacement-coverage",
    "cross-route-interference", "joint-mission-binding", "joint-objective")
ROUTE_SCOPE = "Proposed route and its declared obstacle scope"
NETWORK_SCOPE = "One complete shared physical network and every imported source obstacle"
JOINT_SCOPE = "Complete proposed route set and protected previous route obligations"
BUDGET_SCOPE = "Current newly authored independent round 90-degree elbow budget; protected prior routes excluded"


class ArtifactStore:
    def get(self, root):
        return {"export_path": "prior.ifc" if root.startswith("old") else "current.ifc"}

    def resolve_path(self, path):
        return Path(path).resolve()


def row(identity, status="PASS", scope=ROUTE_SCOPE, witness=None):
    return {"id": identity, "status": status, "scope": scope, "witness": witness or {}}


def route_rows(rid=None, *, gravity=False, engineering=False, nominal=False, extra=()):
    result = []
    for name in ROUTE_CHECKS + tuple(extra):
        status = "NOT_APPLICABLE" if (name == "gravity-slope" and not gravity or
            name == "engineering-service" and not engineering or name == "nominal-fabrication-witness-integrity" and not nominal) else "PASS"
        scope = {"nominal-fabrication-witness-integrity": "Optional exact nominal model proof integrity; no native PASS or pruning authority",
            "physical-interference-and-clearance": "New route versus every source physical obstacle; pre-existing building defects remain outside this local repair claim"}.get(name, ROUTE_SCOPE)
        result.append(row((rid + ":" if rid else "") + name, status, scope))
    return result


def network_request(pressure=False, engineering=True):
    raw = _fixture.network_scenario()
    if pressure:
        physics = raw.pop("physics")
        for key in ("source_kinetic_energy_correction", "sink_kinetic_energy_correction", "fixed_flow_control_assumption"):
            physics.pop(key)
        physics.update(source_total_pressure_pa=100., sink_total_pressures_pa={"sink-a": 0., "sink-b": 0.},
            pressure_reference="TOTAL_PRESSURE_P_PLUS_KINETIC_EXCLUDING_ELEVATION",
            hydraulic_section_interpretation="IDEAL_CIRCULAR_BORE_FROM_NATIVE_ENVELOPE_MINUS_DECLARED_INSULATION",
            loss_model="FIXED_COEFFICIENT_STEADY_INCOMPRESSIBLE", boundary_control_assumption="Test regulated total pressures")
        raw["pressure_driven"] = physics
        for sink in raw["sinks"]:
            sink.pop("available_static_pressure_pa")
    if not engineering:
        raw["target_modality"] = "LOCAL_GEOMETRIC_COORDINATION"
        raw.pop("physics")
    return SharedNetworkScenario.model_validate(raw).model_dump(mode="json", by_alias=True)


def rebind(case):
    case["candidate"]["state_root"] = digest(case["state"])
    case["run"]["base_root"] = digest(case["baseline"])
    case["report"].update(candidate_root=case["candidate"]["state_root"],
        mission_hash=digest(case["state"]["mission"]), rule_hash=case["state"]["mission"]["rule_hash"])
    return case


def make_case(kind="physical_route", *, pressure=False, engineering=False, gravity=False,
              nominal=False, extras=False, prior=False, budget=None):
    scenario = {"target_modality": "ENGINEERING_SERVICE" if engineering else "LOCAL_GEOMETRIC_COORDINATION",
        "system_type": "GRAVITY_DRAINAGE" if gravity else "PRESSURE_PIPE"}
    derived = {}
    state = {"project_id": "project", "sources": [{"sha256": "a" * 64, "immutable_path": "source.ifc"}],
        "routes": [], "physical_networks": [], "derived_artifacts": derived,
        "mission": {"rule_hash": "b" * 64, "objective_weights": {"length_m": 1}}}
    baseline = {"project_id": "project", "routes": []}
    run = {"id": "origin", "project_id": "project", "base_revision": 1, "request": {"mission": {}}}
    if kind == "physical_network":
        scenario = network_request(pressure, engineering)
        run["request"]["mission"] = copy.deepcopy(scenario)
        derived["network_contract"] = {"scenario": scenario}
        state["physical_networks"] = [{"id": "net", "geometry_artifact": "new-net"}]
        results = [row(name, "NOT_APPLICABLE" if name == "network-demand-conditioned-service" and not engineering else "PASS", NETWORK_SCOPE) for name in NETWORK_CHECKS]
        if pressure:
            results.append(row("network-pressure-operating-point", scope=NETWORK_SCOPE))
        if extras:
            derived["export_correspondence"] = {"root": "export"}
            results.append(row("network-export-federation-correspondence", scope=NETWORK_SCOPE))
        boundary = "fixed total-pressure boundaries and minimum deliveries" if pressure else "fixed demands"
        scope = f"SHARED_PHYSICAL_NETWORK: complete local component tree, {boundary} and all source obstacles; whole-building adequacy not certified"
    else:
        extra = []
        if extras:
            scenario.update(source_port_guid="terminal", authorized_opening={"id": "opening"})
            derived["export_correspondence"] = {"root": "export"}
            extra = ["original-terminal-body-attachment", "authorized-host-subtraction", "export-federation-correspondence"]
        ids = ["route"] if kind == "physical_route" else (["prior-b", "prior-a"] if prior else []) + ["new-a", "new-b"]
        state["routes"] = [{"id": rid, "geometry_artifact": "new-" + rid} for rid in ids]
        if nominal:
            derived["fabrication_evidence_by_route"] = {rid: {"fabrication_status": "FAIL"} for rid in ids}
        if kind == "physical_route":
            derived["routing_scenario"] = scenario
            results = route_rows(gravity=gravity, engineering=engineering, nominal=nominal, extra=extra)
            scope = f"{scenario['target_modality']}: proposed route{' and one explicitly authorized host opening' if extras else ' only'}; numerical CAD contract, not whole-building approval"
        else:
            derived["routing_contracts"] = {rid: {"scenario": copy.deepcopy(scenario)} for rid in ids}
            results = [row(name, scope=JOINT_SCOPE) for name in JOINT_CHECKS]
            for rid in ids:
                results.append(row("route-source-binding:" + rid, scope=JOINT_SCOPE))
                results.extend(route_rows(rid, gravity=gravity, engineering=engineering, nominal=nominal, extra=extra))
            if prior:
                baseline["routes"] = [{"id": rid, "geometry_artifact": "old-" + rid} for rid in ids[:2]]
                results.extend(row("prior-artifact-integrity:" + rid, scope=JOINT_SCOPE) for rid in ids[:2])
                results.append(row("prior-physical-preservation:prior-b", scope=JOINT_SCOPE))
            if budget is not None:
                run["request"]["mission"]["max_new_fittings"] = budget
                derived["joint_fitting_budget"] = {"schema": "oma.joint-new-fitting-budget/1", "max_new_fittings": budget}
                results.append(row("joint-new-fitting-budget", scope=BUDGET_SCOPE,
                    witness={"count_complete": True, "per_new_route": {"new-a": 0, "new-b": 0}, "count": 0}))
            scope = "SIMULTANEOUS_ROUTE_SET: all declared routes and source obstacles; numerical CAD contract; whole-building adequacy not certified"
    case = {"store": ArtifactStore(), "candidate": {"kind": kind, "run_id": "origin", "project_id": "project", "base_revision": 1},
        "state": state, "baseline": baseline, "run": run,
        "report": {"status": "PASS", "results": results, "scope": scope, "checker_version": checker_version()}}
    return rebind(case)


def admit(case):
    return validate_physical_report_admission(case["store"], case["candidate"], case["run"], case["state"], case["baseline"], case["report"])


@pytest.mark.parametrize("kind,options", [
    ("physical_route", {}), ("physical_route", {"engineering": True, "gravity": True, "nominal": True, "extras": True}),
    ("physical_network", {}), ("physical_network", {"engineering": True}),
    ("physical_network", {"engineering": True, "pressure": True, "extras": True}),
    ("physical_route_set", {}), ("physical_route_set", {"prior": True, "budget": 0, "nominal": True}),
    ("physical_route_set", {"prior": True, "budget": 1024, "engineering": True, "extras": True})])
def test_independently_declared_complete_scopes_admit_and_every_omission_fails(kind, options):
    case = make_case(kind, **options)
    admitted = admit(case)
    assert admitted["required_checks"] == {r["id"]: r["status"] for r in case["report"]["results"]}
    for i in range(len(case["report"]["results"])):
        narrowed = copy.deepcopy(case)
        narrowed["report"]["results"].pop(i)
        with pytest.raises(IntegrityError): admit(narrowed)


@pytest.mark.parametrize("kind", ["physical_route", "physical_route_set", "physical_network"])
@pytest.mark.parametrize("fault", ["duplicate", "extra", "weaken", "strengthen_na", "header_scope", "leaf_scope", "empty_denominator"])
def test_complete_report_cannot_change_inventory_applicability_or_scope(kind, fault):
    case = make_case(kind)
    rows = case["report"]["results"]
    if fault == "duplicate": rows.append(copy.deepcopy(rows[0]))
    if fault == "extra": rows.append(row("invented"))
    if fault == "weaken": rows[0]["status"] = "NOT_APPLICABLE"
    if fault == "strengthen_na": next(r for r in rows if r["status"] == "NOT_APPLICABLE")["status"] = "PASS"
    if fault == "header_scope": case["report"]["scope"] = "Only one favorable pair"
    if fault == "leaf_scope": rows[0]["scope"] = "A fragment"
    if fault == "empty_denominator": case["state"]["sources"] = []; rebind(case)
    with pytest.raises(IntegrityError): admit(case)


@pytest.mark.parametrize("fault", ["candidate_state", "candidate_project", "state_project", "origin_run", "revision", "baseline", "mission", "rule", "build", "not_pass"])
def test_report_binding_is_to_original_run_and_exact_current_inputs(fault):
    case = make_case()
    if fault == "candidate_state": case["candidate"]["state_root"] = "0" * 64
    if fault == "candidate_project": case["candidate"]["project_id"] = "elsewhere"
    if fault == "state_project": case["state"]["project_id"] = "elsewhere"; rebind(case)
    if fault == "origin_run": case["run"]["id"] = "fresh-recheck-owner"
    if fault == "revision": case["run"]["base_revision"] = 2
    if fault == "baseline": case["baseline"]["routes"].append({"id": "omitted"})
    if fault == "mission": case["report"]["mission_hash"] = "0" * 64
    if fault == "rule": case["report"]["rule_hash"] = "0" * 64
    if fault == "build": case["report"]["checker_version"] = "historical"
    if fault == "not_pass": case["report"]["status"] = "UNKNOWN"
    with pytest.raises(IntegrityError): admit(case)


@pytest.mark.parametrize("fault", ["request_pressure", "contract_pressure", "contract_extra"])
def test_original_network_request_and_state_contract_must_match(fault):
    case = make_case("physical_network", pressure=True, engineering=True)
    if fault == "request_pressure": case["run"]["request"]["mission"]["pressure_driven"]["source_total_pressure_pa"] += 1
    if fault == "contract_pressure": case["state"]["derived_artifacts"]["network_contract"]["scenario"]["pressure_driven"]["source_total_pressure_pa"] += 1; rebind(case)
    if fault == "contract_extra": case["state"]["derived_artifacts"]["network_contract"]["scenario"]["unrequested"] = True; rebind(case)
    with pytest.raises(IntegrityError): admit(case)


@pytest.mark.parametrize("budget", [True, False, -1, 1025, 1.5, "2"])
def test_budget_is_a_bounded_strict_integer(budget):
    with pytest.raises(IntegrityError): admit(make_case("physical_route_set", budget=budget))


@pytest.mark.parametrize("fault", ["prior_count", "missing_new", "boolean_count", "boolean_total", "wrong_total", "over_budget", "incomplete", "stale_budget", "phantom_contract", "duplicate_route"])
def test_zero_budget_requires_exact_new_native_component_count_inventory(fault):
    case = make_case("physical_route_set", budget=0, prior=True)
    witness = next(r["witness"] for r in case["report"]["results"] if r["id"] == "joint-new-fitting-budget")
    if fault == "prior_count": witness["per_new_route"]["prior-a"] = 0
    if fault == "missing_new": witness["per_new_route"].pop("new-a")
    if fault == "boolean_count": witness["per_new_route"]["new-a"] = False
    if fault == "boolean_total": witness["count"] = False
    if fault == "wrong_total": witness["count"] = 1
    if fault == "over_budget": witness["count"] = witness["per_new_route"]["new-a"] = 1
    if fault == "incomplete": witness["count_complete"] = False
    if fault == "stale_budget": case["run"]["request"]["mission"].pop("max_new_fittings")
    if fault == "phantom_contract": case["state"]["derived_artifacts"]["routing_contracts"]["phantom"] = {}; rebind(case)
    if fault == "duplicate_route": case["state"]["routes"].append(copy.deepcopy(case["state"]["routes"][0])); rebind(case)
    with pytest.raises(IntegrityError): admit(case)


@pytest.mark.parametrize("kind", [None, "baseline_check", "analytic", "unrecognized"])
@pytest.mark.parametrize("physical_key", ["sources", "routes", "physical_networks"])
def test_unknown_kind_cannot_disable_physical_admission(kind, physical_key):
    assert requires_physical_report_admission({physical_key: [{"id": "physical"}]}, kind)
    case = make_case()
    case["candidate"]["kind"] = kind
    with pytest.raises(IntegrityError): admit(case)


def test_no_physical_inventory_retains_analytic_protocol_exemption():
    assert not requires_physical_report_admission({"sources": [], "routes": [], "physical_networks": []}, "baseline_check")

