import importlib.util,json,datetime
from pathlib import Path
p=Path(__file__).with_name('audit_completed_suites.py');sp=importlib.util.spec_from_file_location('audit',p);a=importlib.util.module_from_spec(sp);sp.loader.exec_module(a)
base=Path('evidence/release/pressure-admission-complete-c2250254bc084d14abb63f6bf6237c8d');r=json.loads((base/'result.json').read_text());assert r['status']=='PASS'
cbase=Path('evidence/dependencies/native-build/checkpoint-validation/bac10b7f20d4-a70b4635e7d5');c=json.loads((cbase/'result.json').read_text());m=cbase/'test-source-manifest.json';expected=json.loads(m.read_text())['files'];assert a.sha(m)==c['test_source_manifest_sha256'];assert expected==r['snapshot_files'];assert len(expected)==103
nodes_path=Path(c['test_node_manifest']);nodes=nodes_path.read_text().splitlines();assert a.sha(nodes_path)==c['test_node_manifest_sha256'];assert len(nodes)==len(set(nodes))==1722
coll=json.loads(Path(c['test_collection_record']).read_text());assert coll['status']=='PASS' and coll['exit_code']==0
collected=[l for l in (Path(c['test_collection_record']).parent/'output.log').read_text().splitlines() if l.startswith('tests/') and '::' in l];assert collected==nodes
identity=json.loads((cbase/'identity-comparison.json').read_text());source=Path('.oma/runtimes')/c['source_checkpoint']/'src/oma';assert {f.relative_to(source).as_posix():a.sha(f) for f in source.rglob('*.py')}==identity['original']['source_files'];assert a.sha(identity['original']['extension_path'])==identity['original']['extension_sha256'];assert identity['original']['checker_version']==r['checker_version']
result={'status':'ORIGINAL_RETAINED_FULL_SUITE_INDEPENDENTLY_ACCOUNTED','audited_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'script_sha256':a.sha(__file__),'inventory_helper_sha256':a.sha(p),'raw_result_sha256':a.sha(base/'result.json'),'raw_status':r['status'],'checker_version':r['checker_version'],'test_snapshot':a.snapshot(Path(r['test_snapshot']),expected),'xml':a.account_xml(base/'tests.xml',nodes),'node_manifest_sha256':a.sha(nodes_path),'node_collection_record_sha256':a.sha(Path(c['test_collection_record'])),'source_python_files_verified':len(identity['original']['source_files']),'loaded_native_sha256':identity['original']['extension_sha256'],'scope':'Read-only post-completion inventory and exact-node XML reconciliation; no rerun, no custom-native or portable completion claim'}
out=p.with_name('original-completed-audit.json');out.open('x').write(json.dumps(result,indent=2)+'\n');print(json.dumps({'status':result['status'],'passed':result['xml']['passed'],'inputs':len(expected),'derived_outputs':len(result['test_snapshot']['derived_output_sha256']),'sha256':a.sha(out)}))
